apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: learnflow
spec:
  type: pubsub.kafka
  version: v1
  initTimeout: 60s
  metadata:
  - name: brokers
    value: "kafka:9092"
  - name: consumerGroup
    value: "learnflow"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"
